theforumhelpers/theforumhelpers.github.io

- Forum_Helpers/index.html
- index.html
- resources/header.html
Removed all outdated sentences and replaced wrong photos in forum helpers list.
> Continuity Updates

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
Hi!
I'm currently in the process of designing issue templates for this repository. @Accio1, if you think some text needs to be changed please inform me. Issue templates can really make things more clean and better when making new issues. 
If you want, I can also start working on pull request templates.
-Nammy-
> Creating issue templates 

- Forum_Helpers/curators.json
> Updated BGMead's biography

- Forum_Helpers/curators.json
Removed the first usernames from the JSON in order to prevent 54329 from being listed first.
Might close #21
> Fix JSON Curators List

- Forum_Helpers/FHP.js
- Forum_Helpers/index.html
- index.html
- resources/stylesheet.css
This update is focused on making the site more accessable, as well as making it more up to date with best practices according to Google's Lighthouse Audit.
Changelog:
-Added alt text to the profile pictures on the Forum Helpers list page.
-Added language attributes to both the main page and the Forum Helpers list page
-Added viewpoint and description tags to both pages.
Not included in this PR, but added seperately:
-Made the profile pictures of Forum Helpers link to their profiles
-Added "Lazy Image Loading" in order to make the Forum Helpers list page load faster.
> 18/5/20 Accessibility and Performance Updates

- Forum_Helpers/FHP.js
- Forum_Helpers/index.html
- index.html
- resources/header.html
Update File Paths to make it easier to edit locally. This shouldn't impact how anything is displayed on the site, it just makes it easier to update the site locally in the future.
> Update File Paths

- Forum_Helpers/curators.json
- Forum_Helpers/managers.json
Hi! I updated curators.json and managers.json with new curators and I moved the curators that were recently promoted to managers.json.
> New curators and 3 curators promoted to manager

- Forum_Helpers/curators.json
p-p-p-p-p-p-p-p-p-p- and pandacorn_owl have been added, as they just joined the forum helpers.
> p-p-p-p-p-p-p-p-p-p- and pandacorn_owl added

- Forum_Helpers/curators.json
I added a bio for M1mikyu. 
Source: https://scratch.mit.edu/users/M1mikyu/#comments-110102107
> added bio for M1mikyu

- forumhelpers/curators.json
- forumhelpers/managers.json
New bios. They were submitted [here](https://scratch.mit.edu/studios/3688309/comments/#comments-118171662). Ihatr wanted to choose a new bio so it could be added.
> Bio Updates

- forumhelpers/curators.json
Ihatr would like their bio changed. I know that #48 was blocked because you were worried that the person below Ihatr would be upset that their bio was called a lie, but ThatOneWeirdDude (The person under them in the list) gave permission for them to call their bio false [here](https://scratch.mit.edu/studios/3688309/comments/#comments-118325414).
CC: @Accio1
> New bio for Ihatr.

- resources/stylesheet.css
Adds additional CSS to the stylesheet. Mostly font families. I have reviewed this on my end and it looks great.
cc @Accio1
> Fix CSS: Add Additional CSS | Part 3/4 of Fix CSS (#58)

- resources/stylesheet.css
Removes duplicate CSS from the stylesheet. I wasn't able to find a bunch, but I may have missed some.
Final part in Fix CSS. #56 
cc @Accio1
> Fix CSS: Remove Duplicate CSS | Part 4/4 of Fix CSS (#56)

- forumhelpers/curators.json
they are a manager of the main studio and are in managers.json so i removed one of them.
> removed ihatr from curators list

- forumhelpers/curators.json
- forumhelpers/managers.json
Draft PR
Added new curators and bios updated. This PR is marked as a draft because I want to give curators time to send their bios in. At 6:30 PM EST, I'll mark it ready for review.
Closes #78
> New curators and bio updates

- .github/workflows/label.yml
This PR updates the label.yml file to use  on "pull_request_target" instead of on "pull_request", as stated here: https://github.com/actions/labeler/issues/12#issuecomment-670967607
This should resolve #74 
@leahcimto
> Fix Actions Labeller

- resources/stylesheet.css
Removes the font Helvetica as according to https://github.com/theforumhelpers/theforumhelpers.github.io/pull/87#discussion_r588952163 it is not being rendered.
> Remove Helvetica

- contributors/index.html
> remove lankybox01 from contributors page

- forumhelpers/curators.json
- forumhelpers/managers.json
there were about 8 in the curators list but in the managers list poor sigton was the only one lol
resolves #113 #119
> fix no bio provided and new bio for jeffalo

- forumhelpers/curators.json
- forumhelpers/managers.json
Resolves #116. I assigned myself.
Adds wangat to the curator list. No biography was provided in a week.
No, although this is a small change so it should be fine.
> Add wangat to FH List and promote jeffalo 🎉 

- forumhelpers/curators.json
#130 and #133 
Bio for me and -insanitygames-
none, but this is very minor
> Update dogsmakemehappy and -insanitygames- bio

- resources/stylesheet.css
Resolves #123
Adds a margin to the `forumhelpers_navblock` element setting the height to `150px` (Thanks @Accio1)
I tested it locally and it looks good to me!
> Fix margins

- contributors/index.html
Resolves #143
Adds @Shluffy and me as a contributor.
yes, but its not local because I used github pages on my own fork
> Add @Shluffy and @FunctionalMetatable as a contributor

- forumhelpers/curators.json
- forumhelpers/managers.json
Resolves #140
New Curators
None
> Curator Updates

- contributors/index.html
Resolves #146 
Adds Ocular and ScratchDB to the credits page under a new section about services.
Tested locally
@leahcimto
> Add Ocular and ScratchDB

- contributors/index.html
- forumhelpers/FHP.js
_What Github issue does this resolve (please include link)? Do NOT create a Pull Request for a major issue that you have not been assigned to unless you are a part of the editors team for this repo._
Resolves #156 
_Describe what this Pull Request does. Be sure to include a brief description of the issue the Pull Requests solves too._
It solves the fact that people without an ocular status but without a selected ocular color have rings around nothing (see here:)
_Did you test this locally? Example: I tested this via GitHub Desktop and everything looked fine._
It works just fine on Github Desktop, I would appreciate if someone like leahcimto and/or accio could view the changes via [the specific branch on my fork](https://github.com/gosoccerboy5/theforumhelpers.github.io/tree/fill-status) …
> Fill empty ocular status

- contributors/index.html
- resources/stylesheet.css
> Disable Icon Drag

- forumhelpers/FHP.js
- forumhelpers/index.html
- resources/stylesheet.css
Resolves #157 
Thanks to @gosoccerboy5 for suggesting this feature!
-Adds a search bar to the List of Forum Helpers page.
-The search bar border turns red if there is an invalid username and green if the username is valid.
-The search button can only be clicked if the username is valid.
-When the search button is clicked, it will direct the page to that person's username on the page.
Tested locally in both desktop and mobile views.
@gosoccerboy5 I decided to use IDs instead of classnames as you had proposed just because it seemed to make the code a bit more condense. If you have any other features you would like, feel free to suggest them below create a PR to merge into this branch with your changes.
@leahcimto
> Add search bar

- forumhelpers/curators.json
- forumhelpers/managers.json
- forumhelpers/past.json
_What Github issue does this resolve (please include link)? Do NOT create a Pull Request for a major issue that you have not been assigned to unless you are a part of the editors team for this repo._
will totally fix #186
_Describe what this Pull Request does. Be sure to include a brief description of the issue the Pull Requests solves too._
It just removes wherever the json says "helped_code"
_Did you test this locally? Example: I tested this via GitHub Desktop and everything looked fine._
vscode shows no json errors.
> Remove helpedcode

- forumhelpers/curators.json
- forumhelpers/managers.json
- forumhelpers/past.json
Reverts theforumhelpers/theforumhelpers.github.io#206
@gosoccerboy5 this PR broke the Forum Helpers page. This was the error message I got:
Uncaught (in promise) SyntaxError: Unexpected token } in JSON at position 12577
> Revert "Remove helpedcode"

- contributors/index.html
- forumhelpers/past.json
- resources/stylesheet.css
#212 
Adds credit for the taco wizard sprite.
I'm wondering if designerd should be credited. Thoughts on that?
None
> Give Credit to taco wizard sprite

- .github/ISSUE_TEMPLATE/blank.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/theme_suggestion.md
Resolves #223 
Resolves #225 
- Adds a theme suggestions template
- Adds a documentation template
- Fixes the label for the blank template
N/A
> Update Issue Templates

- .github/ISSUE_TEMPLATE/documentation.md
resolves #239 
changes the title part to not be tfh list, but documentations
none.
> Change Documentation issue template

- contributors/index.html
#248 
- Changed order of users based on contributions count
- Added BarelySmooth
Previewed locally
> Update credits page

- resources/stylesheet.css
- resources/theme.js
add some new themes from theme discussion
add the scratch and terminal theme
Known Bugs: 
~~Semicolons should be after the css variables.~~
~~Terminal is spelled terrminal~~
tested ~~but bugs found.~~
> Add new themes

- apply/index.html
Does not resolve an issue, but it seems like applications are open since they are being discussed.
Changes status to open
I did not, since it is such a small change.
> Open Applications

- apply/index.html
- index.html
- resources/imports.js
Resolves part of #280 
- Change studio link to the current studio link.
I used Atom's find and replace tool to replace all of the times the current studio ID was mentioned with the new one. Hopefully none were missed.
> Update Studio Link

- resources/stylesheet.css
https://github.com/theforumhelpers/theforumhelpers.github.io/issues/276#issuecomment-891089570
#276
Fixed the footer to the bottom of the page
Tested via inspect element, it's really only a small change to the css
> Fixed footer to the bottom of the page

- apply/apply.js
- apply/index.html
Integrate applications page with The Forum Helpers Dashboard API.
Doesn't resolve a specific issue, but @leahcimto and I discussed this and thought it would be a good idea.
Announcement about this coming soon!
Tested locally 
@leahcimto
> Add TFH Dashboard Integration

- resources/stylesheet.css
Fixes #258
```
a, button {
transition-duration: 0.4s;
}
```
Compare https://theforumhelpers.github.io/ to https://lankybox01.github.io/theforumhelpers.github.io/ and there you go
> Button transitions

- contributors/index.html
None
Change placement of TheColaber
Add penguinmoose
None
> Credit Page Updates

- apply/index.html
- forumhelpers/FHP.js
- forumhelpers/index.html
Partially fixes #299
Adds placeholder text
Not sure if this is what you all meant by placeholder text, or you wanted to hide the whole sentence and put placeholder text there and then show the whole sentence?
None
> placeholder text

- forumhelpers/FHP.js
Resolves #349
Replaces instances of cdn2 to uploads
> Update avatar URL
