Forum_Helpers/curators.json
After #38 was merged, I noticed that awsome_guy_360's user id was incorrect and their profile picture was not showing. This was my fault, as I pasted their username where the user id should go.
=> awsome_guy_360 user id fixed

Forum_Helpers/FHP.js
Switches the location where images are pulled from to uploads.scratch.mit.edu instead of cdn2.scratch.mit.edu in order to stay up to date with where Scratch is hosting images. This resolves #42 
The following things were reviewed and tested
@leahcimto feel free to leave a review since you were the one who created the issue.
=> Switch from cdn2 to uploads

.github/labeler.yml, .github/workflows/label.yml
Adds GitHub Actions labeller to this repository. This will automatically label pull requests that are created based on the following guidelines:
Any changes- unreviewed
Changes to managers.json or curators.json- Forum Helpers List
Changes to .github folder or README.md or LICENSE file- documentation
The following need to be tested once this is merged:
Resolves #59 
@leahcimto
=> Add labeler

.github/labeler.yml, contributors/contributors.html, contributors/index.html, resources/footer.html, resources/stylesheet.css
Resolves #36 
Change Log:
- Add contributors page sorted in a grid fashion. It is sorted from most to least commits. For the people who contributed outside of commits (eg. issue creation), it is sorted alphabetically. It is generated using JavaScript, so if someone else contributes, their GitHub username can be added to the contributors array and they will be added to the page.
- Added a link to the contributors page and GitHub repository to the footer.
- Made labeler label PRs involving the contributors page as "documentation".
Next Steps: 
- Add more information to the page (eg. what kind of contributions did the person make?)
- Add badges to the list of Forum Helpers page indicating if someone has contributed to the site
@leahcimto
=> Add Contributors Page

forumhelpers/FHP.js, forumhelpers/index.html, forumhelpers/managers.json, resources/stylesheet.css
This resolves #65 and most of #31
-Switch to fetch() instead of XMLRequests
-Add ocular statuses to the list of Forum Helpers page.
-Add the ability to get post counts from ScratchDB, but that seems to be down right now, so it is currently disabled.
-Display the number of curators, managers, and total members on the list of Forum Helpers page.
Tested Locally
@jeffalo @leahcimto
=> Update Forum Helpers Page JavaScript

resources/imports.js, resources/stylesheet.css
_What Github issue does this resolve (please include link)? Do NOT create a Pull Request for a major issue that you have not been assigned to unless you are a part of the editors team for this repo._
This will fix #89 (footer text should be more spaced out).
It also resolves an issue on my machine where there's footer overflow that looks bad.
Screenshot of current TFH build:
_Describe what this Pull Request does. Be sure to include a brief description of the issue the Pull Requests solves too._
This just changes a CSS property (thanks -Accio-), and removes the `<p>` tag from the footer.
With those changes, the footer is perfectly spaced and looks fine.
_Did you test this locally? Example: I tested this via GitHub Desktop and everything looked fine._
Tested locally with Github Desktop, …
=> Make the footer a bit better

404.html
when we switched to using js for the header, the 404 page was not updated
_What Github issue does this resolve (please include link)? Do NOT create a Pull Request for a major issue that you have not been assigned to unless you are a part of the editors team for this repo._
fixes #166
_Describe what this Pull Request does. Be sure to include a brief description of the issue the Pull Requests solves too._
This adds the missing <script> tag that was necessary and also removes the dead \<embed> tag for the header
_Did you test this locally? Example: I tested this via GitHub Desktop and everything looked fine._
Tested locally looks fine, I would appreciate if you could check also
current official build:
This branch on my fork:
=> Update 404 page to have header

contributors/index.html, forumhelpers/index.html, index.html, privacy/index.html, resources/imports.js, resources/stylesheet.css
Does not resolve a specific issue. This was discussed by @Accio1 @leahcimto and @MakeTheBrainHappy as a way to improve the site.
-Adds Google Analytics to track site interactions.
-Adds a privacy warning banner on the bottom of the page when you visit for the first time in a new month.
-Adds a privacy policy and a link to it in the footer.
Tested locally. Note: As far as I know, Google Analytics does not track local usage statistics, so I won't know if the code works until it is on the actual site.
The banner informing about Google Analytics should only show up once. Once you press "Okay" it will not show up again until next month. To test that this works, you can clear local data using the Chrome Inspect Element.
Reviewers: Also feel free to suggest wording changes to the Privacy Policy. …
=> Add Google Analytics and Privacy Policy

404.html, contributors/index.html, forumhelpers/index.html, index.html, privacy/index.html
-Use Universal Analytics instead of GA4 so that the results can be filtered.
Should Resolve #190 
-Use Universal Analytics instead of GA4 so that the results can be filtered.
Not tested locally, since Google Analytics won't work locally. I will test using a fork after this is merged.
@leahcimto
=> Update Google Analytics

404.html, forumhelpers/FHP.js, privacy/index.html, resources/imports.js, resources/stylesheet.css
Resolves #135 
- Adds dark mode to the site by using CSS variables
- The default theme is light mode and there are two themes- light and dark
- In dark mode, the background colours are a dark grey and text is a near-white colour
- Links are a lighter blue for better contrast
- Images and ocular statuses have decreased saturation so they are easier on the eyes
- The button to switch themes is in the footer
- The user's choice is recorded as a localStorage item so the theme is the same the next time they visit the site
- Updates the privacy policy to inform the user of this additional localStorage item
To Do:
- Make the default theme that of the user's device.
- Update the change theme button better (right now it is just a link)
- Add more themes (eg. Scratch Theme)
Tested locally. I also …
=> Add dark mode

404.html, contributors/index.html, forumhelpers/index.html, index.html, privacy/index.html, resources/imports.js, resources/stylesheet.css, resources/theme.js
None.
- Added Button to change theme. It is at the bottom of most pages (except the 404 page - since its a part of the footer)
- That button is still a link! It was just modified to make it look like a button. Also, the ablility to select the element was disabled because anyone repeatedly clicking the button to cycle through themes should be able to do so without it automatically being selected.
- The button also gives information about the current website theme.
- Adds system theme detection. On first launch, if no theme value is set in the cookie, it defaults to the system theme.
- Creates a JS file ```theme.js``` for theme-related Javascript code. It is located in the ```resources``` folder.
- Also, allows a user to switch to system theme. Earlier, it was not possible for the website …
=> Improve theme switch interface

resources/theme.js
A bug introduced in #226 which broke the theme on the the 404 page. The reason this happened was because the code tried to set the ```innerHTML``` of the "Change Theme" button. But since the 404 page didn't have a footer, there was no button and hence it interfered with the theme.
Adds an if statement to change the button's ```innerHTML``` only if the button exists.
I tested this locally (by changing the ```<base>``` tag in ```404.html```). The page then loaded the theme fine.
=> Fix 404 page styling

resources/stylesheet.css
#216 
changes the `--searchBar:` part of `html.darkMode` to `#222b2e` rather then `#1f1f1f`, which blends into the search button when it has a match
#216 contains some screenshots and stuff about how this would work, or see the image below.
=> Change the search bar color in dark mode

resources/imports.js, resources/stylesheet.css
Resolves #236 
-Add two new functions to imports.js: expandHeader() and collapseHeader()
-expandHeader() expands the dropdown that appears on screens <1154px and collapseHeader collapses the dropdown.
-On desktop, hovering on the dropdown will open it and hovering off it will close it.
-On mobile, clicking on the dropdown will open it and clicking somewhere else will close it.
Tested locally, additionally I tested this on my fork of the repo on mobile. This fork can be found here: https://accio1.github.io/theforumhelpers.github.io
@gosoccerboy5 @leahcimto
=> Make header links collapsible on mobile

forumhelpers/FHP.js, forumhelpers/index.html, privacy/index.html, resources/stylesheet.css
Resolves #257 
-Adds a search dropdown
-The search dropdown will display search suggestions based on what a user has typed into the search bar.
-Only 5 suggestions will be shown at once, so typing in "a" will display the first 5 users with "a" in their name.
-Case insensitive
-Clicking on a suggestion will input that user into the search bar.
Tested locally. Feel free to test and see if you can find a way to break it.
The original issue didn't have much discussion, so feel free to suggest changes/additions here. I will leave this PR open for a few days so everyone has the chance to suggest changes.
@leahcimto @jeffalo @gosoccerboy5
=> Add Search Dropdown

apply/index.html, contributors/index.html, index.html, resources/imports.js, resources/stylesheet.css
Resolves #264 
-Add a page with information for potential applicants.
-Applications are currently closed, which is reflected on this page.
-Add a link to the application page in the header.
-Add an information box to the main page directing users to the application page.
-Remove application information from the main page.
-Some small CSS changes to accommodate the changes above.
Tested locally
I'll leave this open for a few days to allow a few people to review it. The content is still subject to change, I just basically took what was in the description before and added it to this page.
@jeffalo @leahcimto @gosoccerboy5
=> Add Application Info Page

.github/PULL_REQUEST_TEMPLATE.md, README.md
Resolves #290.
- Link the CONTRIBUTING.md file in the README.md
- Link it also in the PR template
This way, people are more likely to know about and read the CONTRIBUTING.md file.
Tested the link in the README.md file. It works both locally and on Github's web interface. Also tested the link in the PULL_REQUEST_TEMPLATE.md file locally. It works, I think. [(Thanks!)](https://stackoverflow.com/a/24028813/15938577)
@Accio1 or @leahcimto, if you don't like the text I've used, feel free to edit it.
=> Make the CONTRIBUTING.md file more 'visible'

forumhelpers/curators.json, forumhelpers/managers.json, forumhelpers/originalCurators.json, forumhelpers/originalManagers.json
Resolves #302 
- Moves managers.json and curators.json to originalManagers.json and originalCurators.json.
- Updates managers.json and curators.json with new studio curators list.
- managers.json and curators.json now have a new JSON key that states if the user is in the original studio.
- Adds new bios to managers.json and curators.json that were requested on the [TFH-Bios](https://scratch.mit.edu/users/TFH-Bios/) Scratch account
Tested locally at https://leahcimto.github.io/theforumhelpers.github.io/forumhelpers/. (The latest commit adding new users is not included in this)
fun fact: the dot is very useful
=> Update Forum Helpers JSON Files

forumhelpers/FHP.js
Attempt 2
- Modify FHP.js to retrieve users from database instead of JSON files.
Doesn't resolve an issue, but is necessary for the release of the next TFH Dashboard update.
Announcement and end of downtime coming soon!
Tested locally 
**Please note:** Between the time that this PR is merged and TFH Dashboard downtime ends, the list of Forum Helpers page will not function. Do not worry, this will be resolved when the dashboard is back up.
@leahcimto
=> Integrate List of Forum Helpers with Dashboard

404.html, apply/index.html, contributors/index.html, forumhelpers/index.html, index.html, privacy/index.html, resources/imports.js
Resolves privacy concerns that users may have had
Closes #304 
Closes #271 
- Remove Google Analytics tags from each page
- Remove privacy warning
- Remove Google Analytics from the contributors page
- Modify privacy policy to reflect these changes
Tested locally
@leahcimto
=> Remove Google Analytics

apply/index.html
No issue was resolved, however, upon merging #339, placeholder text was added to places that were blank when the Dashboard API is loading. It looks weird when it says "Applications are Application status loading...", so this fixes that by adding square brackets around "Application status loading". This maybe could also be fixed by changing the wording to "Application status: closed/open/loading", however, this could be a fix for now if that's okay.
See above
None
=> Loading text with brackets around it on apply page

resources/imports.js, resources/stylesheet.css
Resolves #333 
- Make the title in the header a link by wrapping the <a> tag around it
- Make max-width of the header title 37.5% so that the link doesn't overflow the text
Tested locally
@penguinmoose this was your issue so feel free to review.
=> Make header title a link
